{
  imports = [
    ./apcupsd
    ./deluge
    ./docker
    ./fail2ban
    ./flood
    ./grafana
    ./loki
    ./nebula
    ./nginx
    ./nzbget
    ./openssh
    ./overseerr
    ./plex
    ./prometheus
    ./prometheus-apcupsd-exporter
    ./prometheus-node-exporter
    ./prometheus-nginx-exporter
    ./prometheus-snmp-exporter
    ./promtail
    ./prowlarr
    ./pve-exporter
    ./radarr
    ./remote-builder
    ./rtorrent
    ./qbittorrent
    ./sabnzbd
    ./sonarr
    ./tailscale
    ./tautulli
    ./unifi
    ./zerotier
  ];
}
