keys:
  - &user_ethnt age1xgvn6f36rkzmq2kfqx0g2xg90qrpar4hpu6fr8xc3s2kqw6dzqcssnslsv
  - &machine_htpc age1zljvw50qm5mmg5ntstw85aj2pnkswquzmn7c72vudsq4gtepde4qu5s0vd
  - &machine_gateway age148ehmkp9ppddzkpxduv8mc0anr2sdvpjl39hfzza9kaq429kaf9q2vm4af
  - &machine_monitor age1dald4x0rn9pn8fq045twgew3yg7p4lf7w4wyjaftf27t5qkfw39s2pcv59
  - &machine_errata age1jusjemzl3lr7w9wqck7yfdxvlwjlujchm9vwkfgg9cxpdkngesnqecwq5u
  - &machine_matrix age15xjkwphlrg3wrp9g6km8endtsts3pd264njg8jq8ks876rr5t5vsyzn9zd
  - &machine_portal age1zleyd735gdnzuartqnfl23j4v78t3t3x4lyd0q8ncqycpv4dvyjqu4k0a3
  - &machine_branch age1mtxz7kucm9add9q74wac3yjr6d0ffq0l3xgamc899ddzhdkytvsqe4n2qc
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *user_ethnt
          - *machine_htpc
          - *machine_gateway
          - *machine_monitor
          - *machine_errata
          - *machine_matrix
          - *machine_portal
          - *machine_branch

  - path_regex: machines/secrets.yaml$
    key_groups:
      - age:
          - *user_ethnt
          - *machine_htpc
          - *machine_gateway
          - *machine_monitor
          - *machine_errata
          - *machine_matrix
          - *machine_portal
          - *machine_branch
