{
 "title": "Smokeping",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "prober",
    "query": {
     "query": "label_values(smokeping_prober_build_info, instance)"
    }
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(smokeping_response_duration_seconds_bucket, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Smokeping",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(smokeping_response_duration_seconds_bucket{instance=~\"$prober\",host=\"$target\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency - $target",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "smokeping_response_duration_seconds_sum{host=\"$target\"} / smokeping_response_duration_seconds_count{host=\"$target\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Packet Loss - $target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(smokeping_requests_total{host=\"$target\"} - smokeping_response_duration_seconds_count{host=\"$target\"})/smokeping_requests_total{host=\"$target\"} ",
     "legendFormat": "Percentage"
    }
   ]
  }
 ]
}