name: "CI"
on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: orchard
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake -Lv check --show-trace
